/*
 * This file is part of the libsigrok project.
 *
 * Copyright (C) 2026 Nora <sigrok@norabyte.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/*
 * These functions were autogenerated from the programming manual of the UNI-T MSO2204-S,
 * passed through pdftotext.
 * No LLMs were used, just good old-fashioned string-replacements.
 * Unfortunately, during the processing,
 * a lot of errors in the original documentation came to light, especially in the formatting.
 * Therefore, sections (most of which weren't relevant to sigrok anyway) were cut.
*/

#include <glib.h>
#include "scpi.h"
#include "generated_from_programming_manual.h"

char *uni_t_mso2_get_idn(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = "*IDN?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


int uni_t_mso2_set_rst(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = "*RST";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	return SR_OK;
}


char *uni_t_mso2_set_opc(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = "*OPC";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_opc(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = "*OPC?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


int uni_t_mso2_set_run(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":RUN";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	return SR_OK;
}


int uni_t_mso2_set_stop(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":STOP";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	return SR_OK;
}


int uni_t_mso2_set_auto(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":AUTO";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	return SR_OK;
}


char *uni_t_mso2_set_system_lock(const struct sr_dev_inst* sdi, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":SYSTem:LOCK %s", unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_system_lock(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:LOCK?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_system_error(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:ERRor";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_system_error(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:ERRor?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_system_rtc(const struct sr_dev_inst* sdi, const char *year_month_day_hour_minute_second) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":SYSTem:RTC %s", year_month_day_hour_minute_second);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_system_rtc(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:RTC?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


int uni_t_mso2_set_system_cal(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:CAL";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	return SR_OK;
}


int uni_t_mso2_set_system_clear(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:CLEAr";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	return SR_OK;
}


char *uni_t_mso2_set_system_cymometer(const struct sr_dev_inst* sdi, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":SYSTem:CYMOmeter %s", unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_system_cymometer(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:CYMOmeter?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_system_cymometer_frequency(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:CYMOmeter:FREQuency?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_system_square_select(const struct sr_dev_inst* sdi, const char *hz_100hz_1khz_10khz) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":SYSTem:SQUare:SELect %s", hz_100hz_1khz_10khz);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_system_square_select(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:SQUare:SELect?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_system_output_select(const struct sr_dev_inst* sdi, const char *trigger_pass_fail) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":SYSTem:OUTPut:SELect %s", trigger_pass_fail);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_system_output_select(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:OUTPut:SELect?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_system_mnudisplay(const struct sr_dev_inst* sdi, const char *s_10s_20s_infinite) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":SYSTem:MNUDisplay %s", s_10s_20s_infinite);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_system_mnudisplay(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:MNUDisplay?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_system_brightness(const struct sr_dev_inst* sdi, const char *count) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":SYSTem:BRIGhtness %s", count);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_system_brightness(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:BRIGhtness?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_system_version(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:VERSion?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


int uni_t_mso2_set_system_communicate_lan_apply(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:COMMunicate:LAN:APPLy";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	return SR_OK;
}


char *uni_t_mso2_set_system_communicate_lan_gateway(const struct sr_dev_inst* sdi, const char *gateway) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":SYSTem:COMMunicate:LAN:GATEway %s", gateway);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_system_communicate_lan_gateway(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:COMMunicate:LAN:GATEway?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_system_communicate_lan_smask(const struct sr_dev_inst* sdi, const char *submask) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":SYSTem:COMMunicate:LAN:SMASK %s", submask);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_system_communicate_lan_smask(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:COMMunicate:LAN:SMASK?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_system_communicate_lan_ipaddress(const struct sr_dev_inst* sdi, const char *ip) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":SYSTem:COMMunicate:LAN:IPADdress %s", ip);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_system_communicate_lan_ipaddress(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:COMMunicate:LAN:IPADdress?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_system_communicate_lan_dhcp(const struct sr_dev_inst* sdi, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":SYSTem:COMMunicate:LAN:DHCP %s", unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_system_communicate_lan_dhcp(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:COMMunicate:LAN:DHCP?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_system_communicate_lan_mac(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:COMMunicate:LAN:MAC?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_system_auto_channel(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:AUTO:CHANnel";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_system_auto_channel(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:AUTO:CHANnel?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_system_auto_acquire(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:AUTO:ACQuire";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_system_auto_acquire(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:AUTO:ACQuire?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_system_auto_trigger(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:AUTO:TRIGger";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_system_auto_trigger(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:AUTO:TRIGger?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_system_auto_signal(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:AUTO:SIGNal";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_system_auto_signal(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":SYSTem:AUTO:SIGNal?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_channel_bwlimit(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:BWLimit", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_channel_bwlimit(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:BWLimit?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_channel_coupling(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:COUPling", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_channel_coupling(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:COUPling?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_channel_display(const struct sr_dev_inst* sdi, const char *unnamed, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:DISPlay %s", unnamed, channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_channel_display(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:DISPlay?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_channel_invert(const struct sr_dev_inst* sdi, const char *unnamed, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:INVert %s", unnamed, channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_channel_invert(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:INVert?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_channel_probe(const struct sr_dev_inst* sdi, const int channel, const char *probe_0_001x_0_01x_0_1x_1x_10x_100x_1000x) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:PROBe %s", channel + 1, probe_0_001x_0_01x_0_1x_1x_10x_100x_1000x);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_channel_probe(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:PROBe?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_channel_offset(const struct sr_dev_inst* sdi, const char *offset, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:OFFSet %s", offset, channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_channel_offset(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:OFFSet?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_channel_scale(const struct sr_dev_inst* sdi, const char *scale_up_down, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:SCALe %s", scale_up_down, channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_channel_scale(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:SCALe?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_channel_units(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:UNITs", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_channel_units(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:UNITs?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_channel_vernier(const struct sr_dev_inst* sdi, const int channel, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:VERNier %s", channel + 1, unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_channel_vernier(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:VERNier?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_channel_select(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:SELect", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_channel_select(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CHANnel%d:SELect?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_timebase_mode(const struct sr_dev_inst* sdi, const char *main_window) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TIMebase:MODE %s", main_window);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_timebase_mode(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TIMebase:MODE?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_timebase_offset(const struct sr_dev_inst* sdi, const char *offset) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TIMebase:OFFSet %s", offset);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_timebase_offset(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TIMebase:OFFSet?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_timebase_window_offset(const struct sr_dev_inst* sdi, const char *offset) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TIMebase:WINDow:OFFSet %s", offset);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_timebase_window_offset(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TIMebase:WINDow:OFFSet?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_timebase_scale(const struct sr_dev_inst* sdi, const char *scale_up_down) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TIMebase:SCALe %s", scale_up_down);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_timebase_scale(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TIMebase:SCALe?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_timebase_window_scale(const struct sr_dev_inst* sdi, const char *unnamed, const char *scale) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TIMebase:WINDow:SCALe %s %s", unnamed, scale);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_timebase_window_scale(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TIMebase:WINDow:SCALe?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_timebase_indpendent(const struct sr_dev_inst* sdi, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TIMebase:INDPendent %s", unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_timebase_indpendent(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TIMebase:INDPendent?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_timebase_holdoff(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TIMebase:HOLDoff %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_timebase_holdoff(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TIMebase:HOLDoff?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_timebase_split_screen(const struct sr_dev_inst* sdi, const char *off_channel1_channel2_channel3_channel4_all) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TIMebase:SPLit:SCReen %s", off_channel1_channel2_channel3_channel4_all);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_timebase_split_screen(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TIMebase:SPLit:SCReen?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_mode(const struct sr_dev_inst* sdi, const char *mode) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:MODE %s", mode);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_mode(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:MODE?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


int uni_t_mso2_set_trigger_force(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:FORCe";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	return SR_OK;
}


char *uni_t_mso2_set_trigger_sweep(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SWEep";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_trigger_sweep(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SWEep?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


int uni_t_mso2_set_trigger_level_asetup(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:LEVel:ASETup";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	return SR_OK;
}


char *uni_t_mso2_get_trigger_status(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:STATus?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_level(const struct sr_dev_inst* sdi, const char *level) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:LEVel %s", level);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_level(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:LEVel?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_level_low(const struct sr_dev_inst* sdi, const char *level) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:LEVel:LOW %s", level);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_level_low(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:LEVel:LOW?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_level_high(const struct sr_dev_inst* sdi, const char *level) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:LEVel:HIGH %s", level);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_level_high(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:LEVel:HIGH?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_source(const struct sr_dev_inst* sdi, const char *source) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:SOURce %s", source);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_source(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SOURce?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_coupling(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:COUPling";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_trigger_coupling(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:COUPling?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_edge_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:EDGE:SLOPe";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_trigger_edge_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:EDGE:SLOPe?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_pulse_qualifier(const struct sr_dev_inst* sdi, const char *greaterthan_lessthan_inrange) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:PULSe:QUALifier %s", greaterthan_lessthan_inrange);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_pulse_qualifier(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:PULSe:QUALifier?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_pulse_polarity(const struct sr_dev_inst* sdi, const char *positive_negative) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:PULSe:POLarity %s", positive_negative);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_pulse_polarity(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:PULSe:POLarity?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_pulse_time(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:PULSe:TIME %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_pulse_time(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:PULSe:TIME?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_pulse_time_upper(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:PULSe:TIME:UPPer %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_pulse_time_upper(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:PULSe:TIME:UPPer?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_pulse_time_lower(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:PULSe:TIME:LOWer %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_pulse_time_lower(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:PULSe:TIME:LOWer?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_video_mode(const struct sr_dev_inst* sdi, const char *odd_even_line_alines) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:VIDeo:MODE %s", odd_even_line_alines);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_video_mode(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:VIDeo:MODE?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_video_standard(const struct sr_dev_inst* sdi, const char *ntsc_pal_secam) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:VIDeo:STANdard %s", ntsc_pal_secam);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_video_standard(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:VIDeo:STANdard?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_video_line(const struct sr_dev_inst* sdi, const char *value) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:VIDEO:LINE %s", value);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_video_line(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:VIDEO:LINE?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_slope_qualifier(const struct sr_dev_inst* sdi, const char *greaterthan_lessthan_inrange) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:SLOPe:QUALifier %s", greaterthan_lessthan_inrange);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_slope_qualifier(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SLOPe:QUALifier?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_slope_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SLOPe:SLOPe";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_trigger_slope_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SLOPe:SLOPe?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_slope_time(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:SLOPe:TIME %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_slope_time(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SLOPe:TIME?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_slope_time_upper(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:SLOPe:TIME:UPPer %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_slope_time_upper(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SLOPe:TIME:UPPer?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_slope_time_lower(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:SLOPe:TIME:LOWer %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_slope_time_lower(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SLOPe:TIME:LOWer?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_slope_threshold(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SLOPe:THReshold";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_trigger_slope_threshold(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SLOPe:THReshold?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_trigger_slope_rate_lower(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SLOPe:RATe:LOWer?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_trigger_slope_rate_upper(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SLOPe:RATe:UPPer?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_runt_qualifier(const struct sr_dev_inst* sdi, const char *greaterthan_lessthan_inrange_none) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:RUNT:QUALifier %s", greaterthan_lessthan_inrange_none);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_runt_qualifier(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:RUNT:QUALifier?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_runt_polarity(const struct sr_dev_inst* sdi, const char *positive_negative) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:RUNT:POLarity %s", positive_negative);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_runt_polarity(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:RUNT:POLarity?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_runt_level(const struct sr_dev_inst* sdi, const char *low_high_lh) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:RUNT:LEVel %s", low_high_lh);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_runt_level(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:RUNT:LEVel?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_runt_time(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:RUNT:TIME %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_runt_time(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:RUNT:TIME?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_runt_time_upper(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:RUNT:TIME:UPPer %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_runt_time_upper(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:RUNT:TIME:UPPer?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_runt_time_lower(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:RUNT:TIME:LOWer %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_runt_time_lower(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:RUNT:TIME:LOWer?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_window_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:WINDow:SLOPe";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_trigger_window_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:WINDow:SLOPe?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_window_level(const struct sr_dev_inst* sdi, const char *low_high_lh) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:WINDow:LEVel %s", low_high_lh);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_window_level(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:WINDow:LEVel?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_window_time(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:WINDow:TIME %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_window_time(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:WINDow:TIME?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_window_position(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:WINDow:POSition";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_trigger_window_position(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:WINDow:POSition?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_delay_arm_source(const struct sr_dev_inst* sdi, const char *channel1_channel2_channel3_channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:DELay:ARM:SOURce %s", channel1_channel2_channel3_channel);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_delay_arm_source(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:DELay:ARM:SOURce?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_delay_arm_slope(const struct sr_dev_inst* sdi, const char *negative_positive) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:DELay:ARM:SLOPe %s", negative_positive);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_delay_arm_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:DELay:ARM:SLOPe?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_delay_trigger_source(const struct sr_dev_inst* sdi, const char *channel1_channel2_channel3_channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:DELay:TRIGger:SOURce %s", channel1_channel2_channel3_channel);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_delay_trigger_source(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:DELay:TRIGger:SOURce?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_delay_trigger_slope(const struct sr_dev_inst* sdi, const char *negative_positive) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:DELay:TRIGger:SLOPe %s", negative_positive);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_delay_trigger_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:DELay:TRIGger:SLOPe?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_delay_qualifier(const struct sr_dev_inst* sdi, const char *greaterthan_lessthan_inrange_outrange) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:DELay:QUALifier %s", greaterthan_lessthan_inrange_outrange);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_delay_qualifier(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:DELay:QUALifier?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_delay_time(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:DELay:TIME %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_delay_time(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:DELay:TIME?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_delay_time_upper(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:DELay:TIME:UPPer %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_delay_time_upper(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:DELay:TIME:UPPer?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_delay_time_lower(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:DELay:TIME:LOWer %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_delay_time_lower(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:DELay:TIME:LOWer?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_delay_select(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:DELay:SELect";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_timeout_time(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:TIMEOUT:TIME %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_timeout_time(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:TIMEOUT:TIME?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_timeout_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:TIMEOUT:SLOPe";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_trigger_timeout_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:TIMEOUT:SLOPe?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_duration_pattern(const struct sr_dev_inst* sdi, const char *high_low_x) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:DURation:PATTern %s", high_low_x);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_duration_pattern(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:DURation:PATTern?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_duration_qualifier(const struct sr_dev_inst* sdi, const char *greaterthan_lessthan_inrange) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:DURation:QUALifier %s", greaterthan_lessthan_inrange);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_duration_qualifier(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:DURation:QUALifier?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_duration_time_lower(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:DURation:TIME:LOWer %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_duration_time_lower(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:DURation:TIME:LOWer?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_duration_time_upper(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:DURation:TIME:UPPer %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_duration_time_upper(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:DURation:TIME:UPPer?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_shold_data_source(const struct sr_dev_inst* sdi, const char *channel1_channel2_channel3_channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:SHOLd:DATA:SOURce %s", channel1_channel2_channel3_channel);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_shold_data_source(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SHOLd:DATA:SOURce?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_shold_clock_source(const struct sr_dev_inst* sdi, const char *channel1_channel2_channel3_channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:SHOLd:CLOCK:SOURce %s", channel1_channel2_channel3_channel);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_shold_clock_source(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SHOLd:CLOCK:SOURce?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_shold_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SHOLd:SLOPe";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_trigger_shold_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SHOLd:SLOPe?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_shold_pattern(const struct sr_dev_inst* sdi, const char *high_low) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:SHOLd:PATTern %s", high_low);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_shold_pattern(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SHOLd:PATTern?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_shold_mode(const struct sr_dev_inst* sdi, const char *setup_hold_sh) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:SHOLd:MODE %s", setup_hold_sh);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_shold_mode(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SHOLd:MODE?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_shold_time(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:SHOLd:TIME %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_shold_time(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SHOLd:TIME?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_shold_select(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:SHOLd:SELect";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_nedge_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:NEDGE:SLOPe";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_trigger_nedge_slope(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:NEDGE:SLOPe?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_nedge_time(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:NEDGE:TIME %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_nedge_time(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:NEDGE:TIME?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_nedge_value(const struct sr_dev_inst* sdi, const char *value) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:NEDGE:VALue %s", value);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_nedge_value(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:NEDGE:VALue?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_trigger_pattern_pattern(const struct sr_dev_inst* sdi, const char *high_low_x_positive_negative) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":TRIGger:PATTern:PATTern %s", high_low_x_positive_negative);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_trigger_pattern_pattern(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":TRIGger:PATTern:PATTern?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_cursor_mode(const struct sr_dev_inst* sdi, const char *track_independent) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CURSor:MODE %s", track_independent);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_cursor_mode(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:MODE?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_cursor_type(const struct sr_dev_inst* sdi, const char *amplitude_time_screen_close) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CURSor:TYPE %s", amplitude_time_screen_close);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_cursor_type(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:TYPE?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_cursor_source(const struct sr_dev_inst* sdi, const char *source) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CURSor:SOURce %s", source);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_cursor_source(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:SOURce?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_cursor_curax(const struct sr_dev_inst* sdi, const char *value) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CURSor:CURAX %s", value);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_cursor_curax(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:CURAX?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_cursor_curay(const struct sr_dev_inst* sdi, const char *value) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CURSor:CURAY %s", value);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_cursor_curay(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:CURAY?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_cursor_curbx(const struct sr_dev_inst* sdi, const char *value) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CURSor:CURBX %s", value);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_cursor_curbx(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:CURBX?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_cursor_curby(const struct sr_dev_inst* sdi, const char *value) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":CURSor:CURBY %s", value);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_cursor_curby(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:CURBY?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_cursor_axvalue(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:AXValue?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_cursor_ayvalue(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:AYValue?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_cursor_bxvalue(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:BXValue?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_cursor_byvalue(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:BYValue?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_cursor_xdelta(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:XDELta?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_cursor_ydelta(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:YDELta?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_cursor_xy(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":CURSor:XY?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


int uni_t_mso2_set_file_load(const struct sr_dev_inst* sdi, const char *disk, const char *source, const char *filename) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":FILE:LOAD %s %s %s", disk, source, filename);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	g_free(cmd);
	return SR_OK;
}


int uni_t_mso2_set_file_save(const struct sr_dev_inst* sdi, const char *filename, const char *disk, const char *source) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":FILE:SAVE %s %s %s", filename, disk, source);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	g_free(cmd);
	return SR_OK;
}


char *uni_t_mso2_set_record_enable(const struct sr_dev_inst* sdi, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":RECord:ENABle %s", unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_record_enable(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":RECord:ENABle?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_record_start(const struct sr_dev_inst* sdi, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":RECord:STARt %s", unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_record_start(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":RECord:STARt?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_record_fast(const struct sr_dev_inst* sdi, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":RECord:FAST %s", unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_record_fast(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":RECord:FAST?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_record_interval(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":RECord:INTerval %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_record_interval(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":RECord:INTerval?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_record_play(const struct sr_dev_inst* sdi, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":RECord:PLAY %s", unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_record_play(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":RECord:PLAY?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_record_play_delay(const struct sr_dev_inst* sdi, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":RECord:PLAY:DELay %s", time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_record_play_delay(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":RECord:PLAY:DELay?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_record_current(const struct sr_dev_inst* sdi, const char *value) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":RECord:CURRent %s", value);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_record_current(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":RECord:CURRent?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_record_frames(const struct sr_dev_inst* sdi, const char *value) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":RECord:FRAMes %s", value);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_record_frames(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":RECord:FRAMes?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_dvm_enable(const struct sr_dev_inst* sdi, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":DVM:ENABle %s", unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_dvm_enable(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DVM:ENABle?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_dvm_source(const struct sr_dev_inst* sdi, const char *source) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":DVM:SOURCe %s", source);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_dvm_source(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DVM:SOURCe?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_dvm_mode(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DVM:MODE";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_dvm_mode(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DVM:MODE?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_dvm_current(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DVM:CURRent?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_acquire_type(const struct sr_dev_inst* sdi, const char *normal_average_peakdetect_envelope_hresolution) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":ACQuire:TYPE %s", normal_average_peakdetect_envelope_hresolution);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_acquire_type(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":ACQuire:TYPE?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_acquire_averages_count(const struct sr_dev_inst* sdi, const char *count) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":ACQuire:AVERages:COUNt %s", count);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_acquire_averages_count(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":ACQuire:AVERages:COUNt?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_acquire_memory_depth(const struct sr_dev_inst* sdi, const char *auto_700_7k_70k_700k_7m_14m_28m_56m) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":ACQuire:MEMory:DEPTh %s", auto_700_7k_70k_700k_7m_14m_28m_56m);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_acquire_memory_depth(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":ACQuire:MEMory:DEPTh?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_display_data(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DISPlay:DATA?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_display_format(const struct sr_dev_inst* sdi, const char *vectors_dots) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":DISPlay:FORMat %s", vectors_dots);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_display_format(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DISPlay:FORMat?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_display_grid(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DISPlay:GRID";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_display_grid(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DISPlay:GRID?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_display_grid_brightness(const struct sr_dev_inst* sdi, const char *count) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":DISPlay:GRID:BRIGhtness %s", count);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_display_grid_brightness(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DISPlay:GRID:BRIGhtness?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_display_grad_time(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DISPlay:GRAD:TIME";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_display_grad_time(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DISPlay:GRAD:TIME?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_display_color(const struct sr_dev_inst* sdi, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":DISPlay:COLOR %s", unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_display_color(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DISPlay:COLOR?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_display_color_invert(const struct sr_dev_inst* sdi, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":DISPlay:COLOR:INVERt %s", unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_display_color_invert(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DISPlay:COLOR:INVERt?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_display_wave_brightness(const struct sr_dev_inst* sdi, const char *count) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":DISPlay:WAVE:BRIGhtness %s", count);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_display_wave_brightness(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DISPlay:WAVE:BRIGhtness?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


int uni_t_mso2_set_display_clear(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DISPlay:CLEar";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	return SR_OK;
}


char *uni_t_mso2_set_display_type(const struct sr_dev_inst* sdi, const char *xy12_xy13_xy14_xy23_xy24_xy34_yt) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":DISPlay:TYPE %s", xy12_xy13_xy14_xy23_xy24_xy34_yt);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_display_type(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":DISPlay:TYPE?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_waveform_mode(const struct sr_dev_inst* sdi, const char *normal_raw) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":WAVeform:MODE %s", normal_raw);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_waveform_mode(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:MODE?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_waveform_format(const struct sr_dev_inst* sdi, const char *word_byte_ascii) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":WAVeform:FORMat %s", word_byte_ascii);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_waveform_format(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:FORMat?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_waveform_start(const struct sr_dev_inst* sdi, const char *start) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":WAVeform:STARt %s", start);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_waveform_start(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:STARt?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_waveform_stop(const struct sr_dev_inst* sdi, const char *stop) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":WAVeform:STOP %s", stop);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_waveform_stop(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:STOP?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_waveform_source(const struct sr_dev_inst* sdi, const char *channeln_math_dx) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":WAVeform:SOURce %s", channeln_math_dx);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_waveform_source(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:SOURce?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_waveform_points(const struct sr_dev_inst* sdi, const char *points) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":WAVeform:POINts %s", points);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_waveform_points(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:POINts?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_waveform_data(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:DATA?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_waveform_preamble(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:PREamble?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_waveform_xincrement(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:XINCrement?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_waveform_xorigin(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:XORigin?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_waveform_xreference(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:XREFerence?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_waveform_yincrement(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:YINCrement?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_waveform_yorigin(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:YORigin?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_waveform_yreference(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":WAVeform:YREFerence?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


int uni_t_mso2_set_awg_warb_modulate(const struct sr_dev_inst* sdi, const int channel, const char *arb, const char *file) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":AWG:WARB%d:MODulate %s %s", channel + 1, arb, file);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	g_free(cmd);
	return SR_OK;
}


int uni_t_mso2_set_awg_warb_carrier(const struct sr_dev_inst* sdi, const int channel, const char *file, const char *arb) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":AWG:WARB%d:CARRier %s %s", channel + 1, file, arb);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	g_free(cmd);
	return SR_OK;
}


char *uni_t_mso2_set_la_state(const struct sr_dev_inst* sdi, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:STATe %s", unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_state(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":LA:STATe?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_la_active(const struct sr_dev_inst* sdi, const char *dx_channel1_channel2_off) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:ACTive %s", dx_channel1_channel2_off);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_active(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":LA:ACTive?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_la_autosort(const struct sr_dev_inst* sdi, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:AUTOsort %s", unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_autosort(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":LA:AUTOsort?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_la_digital_display(const struct sr_dev_inst* sdi, const int channel, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:DIGital%d:DISPlay %s", channel + 1, unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_digital_display(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:DIGital%d:DISPlay?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_la_digital_position(const struct sr_dev_inst* sdi, const char *position, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:DIGital%d:POSition %s", position, channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_digital_position(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:DIGital%d:POSition?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_la_digital_label(const struct sr_dev_inst* sdi, const int channel, const char *label) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:DIGital%d:LABel %s", channel + 1, label);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_digital_label(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:DIGital%d:LABel?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_la_pod_display(const struct sr_dev_inst* sdi, const int channel, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:POD%d:DISPlay %s", channel + 1, unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_pod_display(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:POD%d:DISPlay?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_la_pod_threshold(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:POD%d:THReshold", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_pod_threshold(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:POD%d:THReshold?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_la_size(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":LA:SIZe";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_la_size(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":LA:SIZe?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_la_tcalibrate(const struct sr_dev_inst* sdi, const char *tcal) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:TCALibrate %s", tcal);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_tcalibrate(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":LA:TCALibrate?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_la_delete(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":LA:DELete";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_get_la_delete(const struct sr_dev_inst* sdi) {
	char *cmd;
	char *output;

	cmd = ":LA:DELete?";
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	return output;
}


char *uni_t_mso2_set_la_group_display(const struct sr_dev_inst* sdi, const int channel, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:GROup%d:DISPlay %s", channel + 1, unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_group_display(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:GROup%d:DISPlay?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


int uni_t_mso2_set_la_group_append(const struct sr_dev_inst* sdi, const char *digital1_digital15, const char *digital0, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:GROup%d:APPend %s %s", digital1_digital15, digital0, channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return SR_ERR;

	g_free(cmd);
	return SR_OK;
}


char *uni_t_mso2_set_la_bus_display(const struct sr_dev_inst* sdi, const int channel, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:DISPlay %s", channel + 1, unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_bus_display(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:DISPlay?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_la_bus_base(const struct sr_dev_inst* sdi, const char *ascii_binary_hex_dec_wav, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:BASE %s", ascii_binary_hex_dec_wav, channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_bus_base(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:BASE?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_la_bus_event(const struct sr_dev_inst* sdi, const int channel, const char *unnamed) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:EVENt %s", channel + 1, unnamed);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_bus_event(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:EVENt?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_bus_data(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:DATA?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_la_bus_slope(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:SLOPe", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_bus_slope(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:SLOPe?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_la_bus_clk(const struct sr_dev_inst* sdi, const int channel, const char *dx_channel1_channel2_off) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:CLK %s", channel + 1, dx_channel1_channel2_off);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_bus_clk(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:CLK?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_la_bus_polarity(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:POLarity", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_bus_polarity(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:POLarity?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_la_bus_nreject(const struct sr_dev_inst* sdi, const char *unnamed, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:NREJect %s", unnamed, channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_bus_nreject(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:NREJect?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_set_la_bus_nrtime(const struct sr_dev_inst* sdi, const int channel, const char *time) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:NRTime %s", channel + 1, time);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


char *uni_t_mso2_get_la_bus_nrtime(const struct sr_dev_inst* sdi, const int channel) {
	char *cmd;
	char *output;

	cmd = g_strdup_printf(":LA:BUS%d:NRTime?", channel + 1);
	if (sr_scpi_get_string(sdi->conn, cmd, &output) != SR_OK)
		return NULL;

	g_free(cmd);
	return output;
}


